# Generated by scripts/gen_skill_refs.py -- do not edit by hand.
# Regenerate: .venv12/bin/python scripts/gen_skill_refs.py --only stubs
# Reference-only type stubs for coding agents; not installed or packaged.

"""Enums, BarData, Portfolio, order/trade/position records, column/indicator scopes, and evaluation result types."""

from collections import deque
from dataclasses import dataclass, field
from datetime import datetime
from decimal import Decimal
from enum import Enum
from typing import (
    Any,
    Callable,
    Iterable,
    Literal,
    Mapping,
    NamedTuple,
    Optional,
    Sequence,
    Union,
)

from numpy.typing import NDArray
import numpy as np
import pandas as pd

from pybroker_context import SlippageModel

# Opaque internal types (referenced by signatures only).
class PriceScope: ...
class SymbolArrayStore: ...

# --- src/pybroker/common.py ---
class DataCol(Enum):
    """Default data column names."""

    DATE = "date"
    SYMBOL = "symbol"
    OPEN = "open"
    HIGH = "high"
    LOW = "low"
    CLOSE = "close"
    VOLUME = "volume"
    VWAP = "vwap"

class Day(Enum):
    """Enumeration of days."""

    MON = 0
    TUES = 1
    WEDS = 2
    THURS = 3
    FRI = 4
    SAT = 5
    SUN = 6

class FeeMode(Enum):
    """Brokerage fee mode to use for backtesting."""

    ORDER_PERCENT = "order_percent"
    PER_ORDER = "per_order"
    PER_SHARE = "per_share"

class OrderType(Enum):
    """Order type classifications."""

    MARKET = "market"
    LIMIT = "limit"
    STOP_BAR = "stop_bar"
    STOP_LOSS = "stop_loss"
    STOP_PROFIT = "stop_profit"
    STOP_TRAILING = "stop_trailing"

class PositionIntent(Enum):
    """Position intent of an order."""

    BUY_TO_OPEN = "buy_to_open"
    BUY_TO_CLOSE = "buy_to_close"
    SELL_TO_OPEN = "sell_to_open"
    SELL_TO_CLOSE = "sell_to_close"

class PositionMode(Enum):
    """Position mode for backtesting."""

    DEFAULT = "default"
    LONG_ONLY = "long_only"
    SHORT_ONLY = "short_only"

class PriceType(Enum):
    """Enumeration of price types used to specify fill price with :class:`pybroker.context.ExecContext`."""

    OPEN = "open"
    LOW = "low"
    HIGH = "high"
    CLOSE = "close"
    MIDDLE = "middle"
    AVERAGE = "average"

class StopType(Enum):
    """Stop types."""

    BAR = "bar"
    LOSS = "loss"
    PROFIT = "profit"
    TRAILING = "trailing"

class BarData:
    """Contains data for a series of bars."""
    def __init__(
        self,
        date: NDArray[np.datetime64],
        open: NDArray[np.float64],
        high: NDArray[np.float64],
        low: NDArray[np.float64],
        close: NDArray[np.float64],
        volume: Optional[NDArray[np.float64]],
        vwap: Optional[NDArray[np.float64]],
        **kwargs,
    ): ...
    # Instance attributes assigned in __init__:
    date: NDArray[np.datetime64]
    open: NDArray[np.float64]
    high: NDArray[np.float64]
    low: NDArray[np.float64]
    close: NDArray[np.float64]
    volume: Optional[NDArray[np.float64]]
    vwap: Optional[NDArray[np.float64]]
    def __getattr__(self, attr): ...  # registered custom columns

class FeeInfo(NamedTuple):
    """Contains info for custom fee calculations."""

    symbol: str
    shares: Decimal
    fill_price: Decimal
    order_type: Literal["buy", "sell"]

class TrainedModel(NamedTuple):
    """Trained model/symbol identifier."""

    name: str
    instance: Any
    predict_fn: Optional[
        Callable[[Any, Union[pd.DataFrame, NDArray]], NDArray]
    ]
    input_cols: Optional[tuple[str]]
    per_bar: bool = False
    lag_columns: Optional[tuple[str, ...]] = None

SymbolSelector = Callable[[pd.DataFrame], Sequence[str]]

# --- src/pybroker/interval.py ---
CalendarInterval = Literal["daily", "weekly", "monthly", "quarterly", "yearly"]

TimeframeInterval = Union[int, CalendarInterval, str]

# --- src/pybroker/portfolio.py ---
class Stop(NamedTuple):
    """Contains information about a stop set on :class:`.Entry`."""

    id: int
    symbol: str
    stop_type: StopType
    pos_type: Literal["long", "short"]
    percent: Optional[Decimal]
    points: Optional[Decimal]
    bars: Optional[int]
    fill_price: Optional[
        Union[
            int,
            float,
            np.floating,
            Decimal,
            PriceType,
            Callable[[str, BarData], Union[int, float, Decimal]],
        ]
    ]
    limit_price: Optional[Decimal]
    exit_price: Optional[PriceType]

@dataclass
class Entry:
    """Contains information about an entry into a :class:`.Position`."""

    id: int
    date: np.datetime64
    symbol: str
    shares: Decimal
    price: Decimal
    type: Literal["long", "short"]
    bars: int = 0
    sym_bars: int = 0
    stops: list[Stop] = list()
    mae: Decimal = Decimal()
    mfe: Decimal = Decimal()

@dataclass
class Position:
    """Contains information about an open position in ``symbol``."""

    symbol: str
    shares: Decimal
    type: Literal["long", "short"]
    close: Decimal = Decimal()
    equity: Decimal = Decimal()
    market_value: Decimal = Decimal()
    margin: Decimal = Decimal()
    pnl: Decimal = Decimal()
    entries: deque[Entry] = deque()
    bars: int = 0
    entry_notional: Decimal = Decimal()
    unmarked_shares: Decimal = Decimal()
    unmarked_notional: Decimal = Decimal()

class Trade(NamedTuple):
    """Holds information about a completed trade (entry and exit)."""

    id: int
    type: Literal["long", "short"]
    symbol: str
    entry_date: np.datetime64
    exit_date: np.datetime64
    entry: Decimal
    exit: Decimal
    shares: Decimal
    pnl: Decimal
    return_pct: Decimal
    agg_pnl: Decimal
    bars: int
    pnl_per_bar: Decimal
    stop: Optional[Literal["bar", "loss", "profit", "trailing"]]
    mae: Decimal
    mfe: Decimal

class Order(NamedTuple):
    """Holds information about a filled order."""

    id: int
    type: Literal["buy", "sell"]
    symbol: str
    date: np.datetime64
    created: Optional[np.datetime64]
    order_type: Literal[
        "market",
        "limit",
        "stop_bar",
        "stop_loss",
        "stop_profit",
        "stop_trailing",
    ]
    intent: Literal[
        "buy_to_open", "buy_to_close", "sell_to_open", "sell_to_close"
    ]
    shares: Decimal
    limit_price: Optional[Decimal]
    market_price: Decimal
    fill_price: Decimal
    fees: Decimal

class PortfolioBar(NamedTuple):
    """Snapshot of :class:`.Portfolio` state, captured per bar."""

    date: np.datetime64
    cash: Decimal
    equity: Decimal
    notional: Decimal
    margin: Decimal
    margin_loan: Decimal
    net_cash_balance: Decimal
    market_value: Decimal
    pnl: Decimal
    unrealized_pnl: Decimal
    fees: Decimal

class PositionBar(NamedTuple):
    """Snapshot of an open :class:`.Position`'s state, captured per bar."""

    symbol: str
    date: np.datetime64
    long_shares: Decimal
    short_shares: Decimal
    close: Decimal
    equity: Decimal
    market_value: Decimal
    margin: Decimal
    unrealized_pnl: Decimal

class Portfolio:
    """Class representing a portfolio of holdings."""
    def __init__(
        self,
        cash: float,
        fee_mode: Optional[
            Union[FeeMode, Callable[[FeeInfo], Decimal], None]
        ] = None,
        fee_amount: Optional[float] = None,
        enable_fractional_shares: bool = False,
        position_mode: PositionMode = PositionMode.DEFAULT,
        max_long_positions: Optional[int] = None,
        max_short_positions: Optional[int] = None,
        record_stops: Optional[bool] = False,
        leverage: float = 1.0,
        interest_rate: float = 0.0,
        bars_per_year: Optional[int] = None,
        record_portfolio_bars: bool = False,
        record_position_bars: bool = False,
    ): ...
    # Instance attributes assigned in __init__:
    cash: Decimal
    equity: Decimal
    market_value: Decimal
    orders: deque[Order]
    trades: deque[Trade]
    margin: Decimal
    pnl: Decimal
    long_positions: dict[str, Position]
    short_positions: dict[str, Position]
    symbols: set[str]
    bars: deque[PortfolioBar]
    position_bars: deque[PositionBar]
    @property
    def margin_loan(self) -> Decimal: ...
    @property
    def win_rate(self) -> Decimal: ...
    @property
    def loss_rate(self) -> Decimal: ...
    def buy(
        self,
        date: np.datetime64,
        symbol: str,
        shares: Decimal,
        fill_price: Decimal,
        limit_price: Optional[Decimal] = None,
        stops: Optional[Iterable[Stop]] = None,
        created: Optional[np.datetime64] = None,
        order_type: OrderType = OrderType.MARKET,
        market_price: Optional[Decimal] = None,
    ) -> Optional[Order]: ...
    def sell(
        self,
        date: np.datetime64,
        symbol: str,
        shares: Decimal,
        fill_price: Decimal,
        limit_price: Optional[Decimal] = None,
        stops: Optional[Iterable[Stop]] = None,
        created: Optional[np.datetime64] = None,
        order_type: OrderType = OrderType.MARKET,
        market_price: Optional[Decimal] = None,
    ) -> Optional[Order]: ...
    def exit_position(
        self,
        date: np.datetime64,
        symbol: str,
        buy_fill_price: Decimal,
        sell_fill_price: Decimal,
        col_scope: Optional[ColumnScope] = None,
        ind_scope: Optional[IndicatorScope] = None,
        sym_end_index: Optional[Mapping[str, int]] = None,
        slippage_model: Optional["SlippageModel"] = None,
    ): ...
    def capture_bar(
        self,
        date: np.datetime64,
        col_scope: ColumnScope,
        sym_end_index: Mapping[str, int],
        price_scope: Optional[PriceScope] = None,
    ): ...
    def incr_bars(
        self,
        date: Optional[np.datetime64] = None,
        price_scope: Optional[PriceScope] = None,
    ): ...
    def remove_stop(self, stop_id: int) -> bool: ...
    def remove_stops(
        self,
        val: Union[str, Position, Entry],
        stop_type: Optional[StopType] = None,
    ): ...
    def check_stops(
        self,
        date: np.datetime64,
        price_scope: PriceScope,
        col_scope: Optional[ColumnScope] = None,
        sym_end_index: Optional[Mapping[str, int]] = None,
        ind_scope: Optional[IndicatorScope] = None,
        slippage_model: Optional["SlippageModel"] = None,
    ): ...

# --- src/pybroker/scope.py ---
class PendingOrder(NamedTuple):
    """Holds data for a pending order."""

    id: int
    type: Literal["buy", "sell"]
    symbol: str
    created: np.datetime64
    exec_date: np.datetime64
    shares: Decimal
    limit_price: Optional[Decimal]
    fill_price: Union[
        int,
        float,
        np.floating,
        Decimal,
        PriceType,
        Callable[[str, BarData], Union[int, float, Decimal]],
    ]
    exec_bar: int
    timeout_bars: Optional[int]
    stops: Optional[frozenset["Stop"]]
    exit_pos_type: Optional[Literal["long", "short"]] = None

class ColumnScope:
    """Caches and retrieves column data from a :class:`SymbolArrayStore`."""
    # Constructed by the framework; not user-instantiable.
    @property
    def store(self) -> SymbolArrayStore: ...
    @property
    def symbols(self) -> frozenset[str]: ...
    def unique_dates(self) -> NDArray[np.datetime64]: ...
    def fetch_dict(
        self,
        symbol: str,
        names: Iterable[str],
        end_index: Optional[int] = None,
    ) -> dict[str, Optional[NDArray]]: ...
    def fetch(
        self, symbol: str, name: str, end_index: Optional[int] = None
    ) -> Optional[NDArray]: ...
    def fetch_value(
        self, symbol: str, name: str, end_index: int
    ) -> Optional[float]: ...
    def bar_data_from_data_columns(
        self, symbol: str, end_index: int
    ) -> BarData: ...

class IndicatorScope:
    """Caches and retrieves :class:`pybroker.indicator.Indicator` data."""
    # Constructed by the framework; not user-instantiable.
    def fetch(
        self, symbol: str, name: str, end_index: Optional[int] = None
    ) -> NDArray[np.float64]: ...
    def fetch_full(self, symbol: str, name: str) -> NDArray[np.float64]: ...
    def has_indicator(self, symbol: str, name: str) -> bool: ...
    def fetch_history(
        self, symbol: str, name: str, dates: NDArray[Any]
    ) -> Optional[NDArray[np.float64]]: ...
    def fetch_value(self, symbol: str, name: str, end_index: int) -> float: ...

# --- src/pybroker/eval.py ---
@dataclass(frozen=True)
class EvalMetrics:
    """Contains metrics for evaluating a :class:`pybroker.strategy.Strategy`."""

    trade_count: int = 0
    initial_market_value: float = 0
    end_market_value: float = 0
    total_pnl: float = 0
    unrealized_pnl: float = 0
    total_return_pct: float = 0
    annual_return_pct: Optional[float] = None
    total_profit: float = 0
    total_loss: float = 0
    total_fees: float = 0
    max_drawdown: float = 0
    max_drawdown_pct: float = 0
    max_drawdown_date: Optional[datetime] = None
    win_rate: float = 0
    loss_rate: float = 0
    winning_trades: int = 0
    losing_trades: int = 0
    avg_pnl: float = 0
    avg_return_pct: float = 0
    avg_trade_bars: float = 0
    avg_profit: float = 0
    avg_profit_pct: float = 0
    avg_winning_trade_bars: float = 0
    avg_loss: float = 0
    avg_loss_pct: float = 0
    avg_losing_trade_bars: float = 0
    largest_win: float = 0
    largest_win_pct: float = 0
    largest_win_bars: int = 0
    largest_loss: float = 0
    largest_loss_pct: float = 0
    largest_loss_bars: int = 0
    max_wins: int = 0
    max_losses: int = 0
    sharpe: float = 0
    sortino: float = 0
    calmar: Optional[float] = None
    profit_factor: float = 0
    ulcer_index: float = 0
    upi: float = 0
    equity_r2: float = 0
    std_error: float = 0
    annual_std_error: Optional[float] = None
    annual_volatility_pct: Optional[float] = None
    def to_json(self) -> dict[str, Any]: ...

class BootConfIntervals(NamedTuple):
    """Holds confidence intervals of bootstrap tests."""

    low_2p5: float
    high_2p5: float
    low_5: float
    high_5: float
    low_10: float
    high_10: float

class DrawdownConfs(NamedTuple):
    """Contains upper bounds of confidence intervals for maximum drawdown."""

    q_001: float
    q_01: float
    q_05: float
    q_10: float

class DrawdownMetrics(NamedTuple):
    """Contains drawdown metrics."""

    confs: DrawdownConfs
    pct_confs: DrawdownConfs

class BootstrapResult(NamedTuple):
    """Contains results of bootstrap tests."""

    conf_intervals: pd.DataFrame
    drawdown_conf: pd.DataFrame
    profit_factor: BootConfIntervals
    sharpe: BootConfIntervals
    drawdown: DrawdownMetrics
    def to_json(self) -> dict[str, Any]: ...
