# Generated by scripts/gen_skill_refs.py -- do not edit by hand.
# Regenerate: .venv12/bin/python scripts/gen_skill_refs.py --only stubs
# Reference-only type stubs for coding agents; not installed or packaged.

"""Strategy, StrategyConfig, TestResult, and the optimization types."""

from dataclasses import dataclass, field
from datetime import datetime
from decimal import Decimal
from typing import Any, Callable, Iterable, Mapping, Optional, Union

from optuna.samplers import BaseSampler
from typing_extensions import Concatenate, ParamSpec
import optuna
import pandas as pd

from pybroker_context import ExecContext, RotationContext, SlippageModel
from pybroker_model import DataSource, Indicator, ModelSource
from pybroker_types import BarData, BootstrapResult, Day, EvalMetrics, FeeInfo, FeeMode, Portfolio, PositionMode, PriceType, SymbolSelector, TimeframeInterval

P = ParamSpec('P')
StrategySetting = Union[int, Hyperparam, None]
_DEFAULT_JSON_INCLUDE = frozenset({'metrics', 'trades', 'orders', 'bootstrap'})

# --- src/pybroker/config.py ---
@dataclass(frozen=True)
class StrategyConfig:
    """Configuration options for :class:`pybroker.strategy.Strategy`."""
    initial_cash: float = 100000
    fee_mode: Optional[Union[FeeMode, Callable[[FeeInfo], Decimal]]] = None
    fee_amount: float = 0
    enable_fractional_shares: bool = False
    round_fill_price: bool = True
    position_mode: PositionMode = PositionMode.DEFAULT
    max_long_positions: Optional[int] = None
    max_short_positions: Optional[int] = None
    buy_delay: int = 1
    sell_delay: int = 1
    bootstrap_samples: int = 10000
    exit_on_last_bar: bool = False
    exit_cover_fill_price: Union[PriceType, Callable[[str, BarData], Union[int, float, Decimal]]] = PriceType.MIDDLE
    exit_sell_fill_price: Union[PriceType, Callable[[str, BarData], Union[int, float, Decimal]]] = PriceType.MIDDLE
    bars_per_year: Optional[int] = None
    return_signals: bool = False
    return_stops: bool = False
    round_test_result: bool = True
    leverage: float = 1.0
    interest_rate: float = 0.0
    record_portfolio_bars: bool = False
    record_position_bars: bool = False

# --- src/pybroker/strategy.py ---
class Strategy:
    """Class representing a trading strategy to backtest."""
    def __init__(self, data_source: Union[DataSource, pd.DataFrame], start_date: Union[str, datetime], end_date: Union[str, datetime], config: Optional[StrategyConfig]=None): ...
    def set_max_long_positions(self, max_long: StrategySetting) -> None: ...
    def set_max_short_positions(self, max_short: StrategySetting) -> None: ...
    def enable_rotation(self, worst_rank_held: StrategySetting, sizer: Optional[Callable[[RotationContext], None]]=None) -> None: ...
    def set_slippage_model(self, slippage_model: Optional[SlippageModel]): ...
    def add_execution(self, fn: Optional[Callable[Concatenate[ExecContext, P], None]], symbols: Union[str, Iterable[str], SymbolSelector], models: Optional[Union[ModelSource, Iterable[ModelSource]]]=None, indicators: Optional[Union[Indicator, Iterable[Indicator]]]=None, hyperparams: Optional[Iterable[Hyperparam]]=None, intervals: Optional[Union[TimeframeInterval, Iterable[TimeframeInterval]]]=None, *args: P.args, **kwargs: P.kwargs): ...
    def set_before_exec(self, fn: Optional[Callable[[Mapping[str, ExecContext]], None]]): ...
    def set_after_exec(self, fn: Optional[Callable[[Mapping[str, ExecContext]], None]]): ...
    def clear_executions(self): ...
    def backtest(self, start_date: Optional[Union[str, datetime]]=None, end_date: Optional[Union[str, datetime]]=None, timeframe: str='', between_time: Optional[tuple[str, str]]=None, days: Optional[Union[str, Day, Iterable[Union[str, Day]]]]=None, lookahead: int=1, train_size: float=0, shuffle: bool=False, calc_bootstrap: bool=False, parallel_indicators: bool=False, parallel_models: bool=False, warmup: Optional[int]=None, portfolio: Optional[Portfolio]=None, adjust: Optional[Any]=None, seed: Optional[int]=42, params: Optional[dict[str, Any]]=None) -> TestResult: ...
    def walkforward(self, windows: int, lookahead: int=1, start_date: Optional[Union[str, datetime]]=None, end_date: Optional[Union[str, datetime]]=None, timeframe: str='', between_time: Optional[tuple[str, str]]=None, days: Optional[Union[str, Day, Iterable[Union[str, Day]]]]=None, train_size: float=0.5, shuffle: bool=False, calc_bootstrap: bool=False, parallel_indicators: bool=False, parallel_models: bool=False, warmup: Optional[int]=None, portfolio: Optional[Portfolio]=None, adjust: Optional[Any]=None, seed: Optional[int]=42, params: Optional[dict[str, Any]]=None) -> TestResult: ...
    def optimize(self, score_fn: Callable[[TestResult], float], *, sampler: Union[str, BaseSampler]='grid', n_trials: Optional[int]=None, direction: str='maximize', seed: Optional[int]=None, windows: Optional[int]=None, study: Optional[optuna.Study]=None, pruner: Optional[optuna.pruners.BasePruner]=None, train_size: float=0.5, lookahead: int=1, start_date: Optional[Union[str, datetime]]=None, end_date: Optional[Union[str, datetime]]=None, timeframe: str='', between_time: Optional[tuple[str, str]]=None, days: Optional[Any]=None, warmup: Optional[int]=None, parallel_indicators: bool=False, adjust: Optional[Any]=None, calc_bootstrap: bool=False, verbose: bool=False) -> OptimizeResult: ...  # from OptimizeMixin (src/pybroker/optimize.py)

@dataclass(frozen=True)
class TestResult:
    """Contains the results of backtesting a :class:`.Strategy`."""
    start_date: datetime
    end_date: datetime
    portfolio: pd.DataFrame
    positions: pd.DataFrame
    orders: pd.DataFrame
    trades: pd.DataFrame
    metrics: EvalMetrics
    metrics_df: pd.DataFrame
    bootstrap: Optional[BootstrapResult]
    signals: Optional[dict[str, pd.DataFrame]]
    stops: Optional[pd.DataFrame]
    def to_json(self, *, include: frozenset[str]=_DEFAULT_JSON_INCLUDE, max_rows: Optional[int]=100, symbols: Optional[frozenset[str]]=None) -> dict[str, Any]: ...
    def to_json_str(self, *, include: frozenset[str]=_DEFAULT_JSON_INCLUDE, max_rows: Optional[int]=100, symbols: Optional[frozenset[str]]=None) -> str: ...

# --- src/pybroker/optimize.py ---
@dataclass(frozen=True)
class Hyperparam:
    """Declares a named hyperparameter with bounds and step size."""
    name: str
    default: Union[int, float]
    low: Union[int, float]
    high: Union[int, float]
    step: Union[int, float]

def hyperparam(name: str, *, default: Union[int, float], low: Union[int, float], high: Union[int, float], step: Union[int, float]) -> Hyperparam:
    """Creates and registers a :class:`Hyperparam`."""

@dataclass(frozen=True)
class OptimizeResult:
    """Result of ``Strategy.optimize()``."""
    best_params: dict[str, Any]
    best_score: float
    result: TestResult
    study: optuna.Study
    windows: Optional[tuple[WindowOptimizeResult, ...]] = None
    def to_json(self, *, include: Optional[frozenset[str]]=None, max_rows: Optional[int]=100, symbols: Optional[frozenset[str]]=None) -> dict[str, Any]: ...
    def to_json_str(self, *, include: Optional[frozenset[str]]=None, max_rows: Optional[int]=100, symbols: Optional[frozenset[str]]=None) -> str: ...

@dataclass(frozen=True)
class WindowOptimizeResult:
    """Per-window walk-forward optimization result."""
    params: dict[str, Any]
    study: optuna.Study
    train_score: float
    train_start_date: Optional[datetime] = None
    train_end_date: Optional[datetime] = None
    test_start_date: Optional[datetime] = None
    test_end_date: Optional[datetime] = None
    execution_symbols: Optional[dict[int, frozenset[str]]] = None
    def to_json(self) -> dict[str, Any]: ...
    def to_json_str(self) -> str: ...
