"""Regenerates the reference files bundled with the PyBroker agent skills.

Rebuilds, deterministically from local sources, for each skill listed in
``SKILLS`` (under ``skills/<name>/references/``):

- ``wiki-*.md`` mirrors of the documentation notebooks in
  ``docs/source/notebooks/`` — every notebook for full-wiki skills, or
  only the wiki files a subset skill already bundles.
- ``api-public-surface.md`` from the public signatures and docstrings in
  ``src/pybroker/`` (identical content for every skill bundling it).
- ``pybroker_*.pyi`` type-stub references from the classes and functions
  registered in ``STUBS`` (identical content for every skill bundling
  them). The stubs are reference documents for coding agents — valid
  ``.pyi`` syntax, but never installed or packaged. Verify them by hand
  with ``mypy --ignore-missing-imports pybroker_*.pyi`` (from a venv on
  the tooling Python) from inside a skill's ``references/`` directory.
- The "User Guide Wiki" entry block of ``wiki-index.md``, for skills
  whose index is generator-owned.

Run with a project venv on the tooling Python (3.12, see
``.github/python-versions.json``) so output is stable across machines
(``ast.unparse`` formatting differs between Python versions)::

    <venv>/bin/python scripts/gen_skill_refs.py
    ruff format skills/*/references/*.pyi
    <venv>/bin/python scripts/gen_skill_refs.py --check

``--check`` rebuilds everything in memory and exits non-zero if any
generated file on disk differs, without writing. This module does not
invoke ruff itself: the raw ``ast.unparse`` output for the ``.pyi`` stubs
uses single quotes and omits blank lines after class docstrings, which
disagrees with the project's ruff style, so a ``ruff format`` pass over
the generated stubs is required before ``--check`` (or a commit) will
pass cleanly.
"""

from __future__ import annotations

import argparse
import ast
import builtins
import re
import sys
from pathlib import Path
from typing import Iterable, Optional

import nbformat

WIKI_BOILERPLATE = (
    "This reference was generated from the local PyBroker documentation "
    "notebook. Use it as the detailed wiki page for this topic."
)
API_HEADER = """\
# Public API Surface

Source: `src/pybroker`

Generated from local source signatures and first docstring sentences. \
Use this with the wiki pages when exact PyBroker names, parameters, \
constructors, and methods matter.
"""
LOGGER_OMISSION_NOTE = (
    "_Status-logging methods omitted (not needed for strategy code)._"
)
INDEX_ENTRIES_START = "## User Guide Wiki"
INDEX_ENTRIES_END = "## API And Pattern References"

# Per-skill generation config. "all_wikis" skills mirror every notebook
# (new pages appear automatically; renamed ones are cleaned up); other
# skills refresh only the wiki files they already bundle. "index" marks
# the wiki-index.md entry block as generator-owned; hand-curated indexes
# with extra routing keywords stay hand-maintained.
SKILLS: dict[str, dict[str, bool]] = {
    "pybroker-strategy-creator": {
        "all_wikis": True,
        "index": True,
        "stubs": True,
    },
    "pybroker-indicator-creator": {
        "all_wikis": False,
        "index": False,
        "stubs": True,
    },
    "pybroker-model-trainer": {
        "all_wikis": False,
        "index": False,
        "stubs": True,
    },
    "pybroker-optimize": {
        "all_wikis": False,
        "index": False,
        "stubs": True,
    },
    "pybroker-multi-interval": {
        "all_wikis": False,
        "index": False,
        "stubs": True,
    },
    "pybroker-rotational-trading": {
        "all_wikis": False,
        "index": False,
        "stubs": True,
    },
}

STUB_HEADER = """\
# Generated by scripts/gen_skill_refs.py -- do not edit by hand.
# Regenerate: <venv>/bin/python scripts/gen_skill_refs.py --only stubs
# Reference-only type stubs for coding agents; not installed or packaged.
"""

# One-line module docstring per stub file.
STUB_TOPICS: dict[str, str] = {
    "pybroker_context.pyi": (
        "Context types passed to strategy code: ExecContext (with its "
        "writable order/stop attributes), IntervalContext, "
        "RotationContext, ExecResult, and the slippage models."
    ),
    "pybroker_strategy.pyi": (
        "Strategy, StrategyConfig, TestResult, and the optimization types."
    ),
    "pybroker_types.pyi": (
        "Enums, BarData, Portfolio, order/trade/position records, "
        "column/indicator scopes, and evaluation result types."
    ),
    "pybroker_model.pyi": (
        "model()/indicator() factories, vector helpers, data sources, "
        "and top-level module functions."
    ),
}

# Stub filename -> ordered [(source path relative to repo, [names])].
# Names may be classes, functions, or top-level alias assignments. A
# registered name missing from its module fails loudly.
STUBS: dict[str, list[tuple[str, list[str]]]] = {
    "pybroker_context.pyi": [
        (
            "src/pybroker/context.py",
            [
                "ExecResult",
                "IntervalContext",
                "ExecContext",
                "RotationContext",
            ],
        ),
        (
            "src/pybroker/slippage.py",
            [
                "SlippageContext",
                "SlippageModel",
                "FixedSlippageModel",
                "VolatilitySlippageModel",
                "VolumeSlippageModel",
            ],
        ),
    ],
    "pybroker_strategy.pyi": [
        ("src/pybroker/config.py", ["StrategyConfig"]),
        ("src/pybroker/strategy.py", ["Strategy", "TestResult"]),
        (
            "src/pybroker/optimize.py",
            [
                "Hyperparam",
                "hyperparam",
                "OptimizeResult",
                "WindowOptimizeResult",
            ],
        ),
    ],
    "pybroker_types.pyi": [
        (
            "src/pybroker/common.py",
            [
                "DataCol",
                "Day",
                "FeeMode",
                "OrderType",
                "PositionIntent",
                "PositionMode",
                "PriceType",
                "StopType",
                "BarData",
                "FeeInfo",
                "TrainedModel",
                "SymbolSelector",
            ],
        ),
        (
            "src/pybroker/interval.py",
            ["CalendarInterval", "TimeframeInterval"],
        ),
        (
            "src/pybroker/portfolio.py",
            [
                "Stop",
                "Entry",
                "Position",
                "Trade",
                "Order",
                "PortfolioBar",
                "PositionBar",
                "Portfolio",
            ],
        ),
        (
            "src/pybroker/scope.py",
            ["PendingOrder", "ColumnScope", "IndicatorScope"],
        ),
        (
            "src/pybroker/eval.py",
            [
                "EvalMetrics",
                "BootConfIntervals",
                "DrawdownConfs",
                "DrawdownMetrics",
                "BootstrapResult",
            ],
        ),
    ],
    "pybroker_model.pyi": [
        (
            "src/pybroker/model.py",
            [
                "ModelSource",
                "IntervalBoundModel",
                "ModelLoader",
                "ModelTrainer",
                "model",
            ],
        ),
        (
            "src/pybroker/indicator.py",
            [
                "Indicator",
                "IntervalBoundIndicator",
                "IndicatorSet",
                "indicator",
                "highest",
                "lowest",
                "returns",
            ],
        ),
        (
            "src/pybroker/vect.py",
            ["atr", "cross", "highv", "lowv", "returnv", "sumv"],
        ),
        (
            "src/pybroker/data.py",
            ["DataSource", "Alpaca", "AlpacaCrypto", "YFinance"],
        ),
        ("src/pybroker/ext/data.py", ["AKShare", "YQuery"]),
        ("src/pybroker/interval.py", ["compress_bars"]),
        (
            "src/pybroker/scope.py",
            [
                "register_columns",
                "unregister_columns",
                "param",
                "clear_params",
                "enable_logging",
                "disable_logging",
                "enable_progress_bar",
                "disable_progress_bar",
            ],
        ),
        (
            "src/pybroker/cache.py",
            [
                "enable_caches",
                "disable_caches",
                "clear_caches",
                "enable_data_source_cache",
                "disable_data_source_cache",
                "clear_data_source_cache",
                "enable_indicator_cache",
                "disable_indicator_cache",
                "clear_indicator_cache",
                "enable_model_cache",
                "disable_model_cache",
                "clear_model_cache",
            ],
        ),
        (
            "src/pybroker/parallel.py",
            ["ParallelConfig", "set_parallel", "get_parallel_config"],
        ),
    ],
}

# Framework-constructed classes: omit __init__ (its parameters are
# internal scope objects) and mark them not user-instantiable.
STUB_NO_INIT = frozenset(
    {"ExecContext", "IntervalContext", "ColumnScope", "IndicatorScope"}
)

# Internal classes referenced by public signatures but not worth
# expanding; emitted as opaque one-liners in STUB_OPAQUE_HOME.
STUB_OPAQUE = frozenset({"SymbolArrayStore", "PriceScope"})
STUB_OPAQUE_HOME = "pybroker_types.pyi"

# class name -> [(source path, mixin class, [method names])] to append
# to the class body (public API inherited from unrendered mixins).
STUB_EXTRA_METHODS: dict[str, list[tuple[str, str, list[str]]]] = {
    "Strategy": [("src/pybroker/optimize.py", "OptimizeMixin", ["optimize"])],
}

# (class name, member name) pairs withheld from every generated
# reference: deprecated members stay out of the API surface and stubs so
# the skills teach only the current API (ctx.long_score / ctx.short_score).
OMIT_MEMBERS = frozenset({("ExecResult", "score"), ("ExecContext", "score")})


def _notebook_paths(notebooks_dir: Path) -> list[Path]:
    """Numeric sort on the leading integer; unnumbered (FAQs) last."""

    def sort_key(path: Path) -> tuple[int, str]:
        match = re.match(r"(\d+)\.", path.name)
        return (
            (int(match.group(1)), path.name) if match else (10**6, path.name)
        )

    return sorted(notebooks_dir.glob("*.ipynb"), key=sort_key)


def _wiki_title(stem: str) -> str:
    """Title-case preserving interior capitals ("FAQs", not "Faqs")."""
    stripped = re.sub(r"^\d+\.\s*", "", stem)
    return " ".join(w[:1].upper() + w[1:] for w in stripped.split(" "))


def _wiki_filename(nb_path: Path) -> str:
    stripped = re.sub(r"^\d+\.\s*", "", nb_path.stem)
    slug = re.sub(r"[^a-z0-9-]", "", stripped.lower().replace(" ", "-"))
    match = re.match(r"(\d+)\.", nb_path.stem)
    if match:
        return f"wiki-{int(match.group(1)):02d}-{slug}.md"
    return f"wiki-{slug}.md"


def _render_wiki(nb_path: Path, nb: nbformat.NotebookNode) -> str:
    blocks = [
        f"# {_wiki_title(nb_path.stem)}",
        f"Source: `docs/source/notebooks/{nb_path.name}`",
        WIKI_BOILERPLATE,
    ]
    for cell in nb.cells:
        source = cell.source.rstrip()
        if not source.strip():
            continue
        if cell.cell_type == "markdown":
            blocks.append(source)
        elif cell.cell_type == "code":
            blocks.append(f"```python\n{source}\n```")
    return "\n\n".join(blocks) + "\n"


def _code_cell_count(nb: nbformat.NotebookNode) -> int:
    return sum(
        1
        for cell in nb.cells
        if cell.cell_type == "code" and cell.source.strip()
    )


def _headings(nb: nbformat.NotebookNode, max_level: int) -> list[str]:
    found = []
    for cell in nb.cells:
        if cell.cell_type != "markdown":
            continue
        in_fence = False
        for line in cell.source.splitlines():
            if line.lstrip().startswith("```"):
                in_fence = not in_fence
                continue
            if in_fence:
                continue
            match = re.match(r"^(#{1,6})\s+(.*?)\s*$", line)
            if match and len(match.group(1)) <= max_level:
                found.append(match.group(2))
    return found


def _index_entry(nb_path: Path, nb: nbformat.NotebookNode) -> str:
    fname = _wiki_filename(nb_path)
    title = _wiki_title(nb_path.stem)
    # The FAQs page routes by question, so index its H3 questions too.
    max_level = 3 if nb_path.stem == "FAQs" else 2
    topics = _headings(nb, max_level)
    return (
        f"- `{fname}` - {title}; {_code_cell_count(nb)} code cells.\n"
        f"  Topics: {'; '.join(topics)}."
    )


def _spliced_index(index_path: Path, entries: list[str]) -> str:
    text = index_path.read_text()
    pre, found_start, rest = text.partition(INDEX_ENTRIES_START)
    mid, found_end, post = rest.partition(INDEX_ENTRIES_END)
    if not found_start or not found_end:
        raise SystemExit(
            f"{index_path}: expected '{INDEX_ENTRIES_START}' and "
            f"'{INDEX_ENTRIES_END}' section headers"
        )
    block = "\n\n".join(entries)
    return (
        f"{pre}{INDEX_ENTRIES_START}\n\n{block}\n\n{INDEX_ENTRIES_END}{post}"
    )


def _first_sentence(doc: Optional[str]) -> Optional[str]:
    if not doc:
        return None
    text = " ".join(doc.strip().split())
    match = re.search(r"\.(?=\s|$)", text)
    return text[: match.end()] if match else text


def _fmt_arg(arg: ast.arg, default: Optional[ast.expr]) -> str:
    out = arg.arg
    if arg.annotation is not None:
        out += f": {ast.unparse(arg.annotation)}"
    if default is not None:
        out += f"={ast.unparse(default)}"
    return out


def _fmt_args(args: ast.arguments, skip_self: bool = False) -> str:
    parts: list[str] = []
    positional = args.posonlyargs + args.args
    defaults: list[Optional[ast.expr]] = [
        *([None] * (len(positional) - len(args.defaults))),
        *args.defaults,
    ]
    for i, (arg, default) in enumerate(zip(positional, defaults)):
        if skip_self and i == 0 and arg.arg in ("self", "cls"):
            continue
        parts.append(_fmt_arg(arg, default))
    if args.vararg is not None:
        parts.append("*" + _fmt_arg(args.vararg, None))
    elif args.kwonlyargs:
        parts.append("*")
    for arg, default in zip(args.kwonlyargs, args.kw_defaults):
        parts.append(_fmt_arg(arg, default))
    if args.kwarg is not None:
        parts.append("**" + _fmt_arg(args.kwarg, None))
    return ", ".join(parts)


def _decorator_names(node: ast.FunctionDef) -> list[str]:
    names = []
    for deco in node.decorator_list:
        target = deco.func if isinstance(deco, ast.Call) else deco
        names.append(ast.unparse(target))
    return names


def _is_public_def(node: ast.stmt) -> bool:
    return isinstance(node, ast.FunctionDef) and (
        not node.name.startswith("_") or node.name == "__call__"
    )


def _fn_bullet(node: ast.FunctionDef, skip_self: bool) -> str:
    sig = f"{node.name}({_fmt_args(node.args, skip_self=skip_self)})"
    if node.returns is not None:
        sig += f" -> {ast.unparse(node.returns)}"
    sentence = _first_sentence(ast.get_docstring(node))
    return f"- `{sig}`: {sentence}" if sentence else f"- `{sig}`"


def _property_bullets(node: ast.FunctionDef) -> str:
    decorators = _decorator_names(node)
    if "property" in decorators or "cached_property" in decorators:
        sig = f"{node.name}()"
        if node.returns is not None:
            sig += f" -> {ast.unparse(node.returns)}"
        sentence = _first_sentence(ast.get_docstring(node))
        return f"- `{sig}`: {sentence}" if sentence else f"- `{sig}`"
    # Setter: value parameter only, no docstring sentence.
    value_args = [a for a in node.args.args if a.arg not in ("self", "cls")]
    params = ", ".join(_fmt_arg(a, None) for a in value_args)
    return f"- `{node.name}({params})`"


def _unwrap_field_default(value: Optional[ast.expr]) -> Optional[str]:
    if value is None:
        return None
    if (
        isinstance(value, ast.Call)
        and isinstance(value.func, ast.Name)
        and value.func.id == "field"
    ):
        for kw in value.keywords:
            if kw.arg == "default":
                return ast.unparse(kw.value)
            if kw.arg == "default_factory":
                return f"{ast.unparse(kw.value)}()"
        return None
    return ast.unparse(value)


def _field_bullets(cls: ast.ClassDef) -> list[str]:
    bullets = []
    for node in cls.body:
        if not isinstance(node, ast.AnnAssign):
            continue
        if not isinstance(node.target, ast.Name):
            continue
        name = node.target.id
        if name.startswith("_") or (cls.name, name) in OMIT_MEMBERS:
            continue
        annotation = ast.unparse(node.annotation)
        if annotation.startswith("ClassVar"):
            continue
        entry = f"{name}: {annotation}"
        default = _unwrap_field_default(node.value)
        if default is not None:
            entry += f" = {default}"
        bullets.append(f"- `{entry}`")
    return bullets


def _is_fieldlike_class(cls: ast.ClassDef) -> bool:
    for deco in cls.decorator_list:
        target = deco.func if isinstance(deco, ast.Call) else deco
        if ast.unparse(target).split(".")[-1] == "dataclass":
            return True
    return any(
        ast.unparse(base).split(".")[-1] == "NamedTuple" for base in cls.bases
    )


def _find_init(cls: ast.ClassDef) -> Optional[ast.FunctionDef]:
    return next(
        (
            node
            for node in cls.body
            if isinstance(node, ast.FunctionDef) and node.name == "__init__"
        ),
        None,
    )


def _init_attrs(cls: ast.ClassDef) -> list[tuple[str, ast.expr]]:
    """Public instance attributes assigned in ``__init__``, in source
    order: ``self.name: T = ...`` annotated assignments, plus plain
    ``self.name = param`` aliases of annotated ``__init__`` parameters.
    """
    init = _find_init(cls)
    if init is None:
        return []
    args = init.args
    params = {
        arg.arg: arg.annotation
        for arg in [*args.posonlyargs, *args.args, *args.kwonlyargs]
        if arg.annotation is not None
    }

    def self_attr(target: ast.expr) -> Optional[str]:
        if (
            isinstance(target, ast.Attribute)
            and isinstance(target.value, ast.Name)
            and target.value.id == "self"
            and not target.attr.startswith("_")
        ):
            return target.attr
        return None

    attrs: list[tuple[str, ast.expr]] = []
    seen: set[str] = set()
    for node in init.body:
        if isinstance(node, ast.AnnAssign):
            name = self_attr(node.target)
            if name is not None and name not in seen:
                seen.add(name)
                attrs.append((name, node.annotation))
        elif isinstance(node, ast.Assign) and len(node.targets) == 1:
            name = self_attr(node.targets[0])
            if (
                name is not None
                and name not in seen
                and isinstance(node.value, ast.Name)
                and node.value.id in params
            ):
                seen.add(name)
                attrs.append((name, params[node.value.id]))
    return attrs


def _root_name(expr: ast.expr) -> Optional[str]:
    while isinstance(expr, ast.Attribute):
        expr = expr.value
    return expr.id if isinstance(expr, ast.Name) else None


def _collect_names(
    expr: Optional[ast.AST], used: set[str], parse_strings: bool = True
) -> None:
    """Gathers root identifiers referenced by an annotation/expression.

    ``parse_strings`` treats string constants as forward-reference
    annotations (except inside ``Literal[...]``, whose strings are
    values); disable it for default values.
    """
    if expr is None:
        return
    if isinstance(expr, ast.Name):
        used.add(expr.id)
        return
    if isinstance(expr, ast.Attribute):
        root = _root_name(expr)
        if root is not None:
            used.add(root)
        return
    if isinstance(expr, ast.Subscript) and _root_name(expr.value) == "Literal":
        _collect_names(expr.value, used, parse_strings)
        return
    if isinstance(expr, ast.Constant):
        if parse_strings and isinstance(expr.value, str):
            try:
                parsed = ast.parse(expr.value, mode="eval")
            except SyntaxError:
                return
            _collect_names(parsed.body, used, parse_strings)
        return
    for child in ast.iter_child_nodes(expr):
        _collect_names(child, used, parse_strings)


def _collect_def_names(node: ast.FunctionDef, used: set[str]) -> None:
    args = node.args
    annotated = [*args.posonlyargs, *args.args, *args.kwonlyargs]
    if args.vararg is not None:
        annotated.append(args.vararg)
    if args.kwarg is not None:
        annotated.append(args.kwarg)
    for arg in annotated:
        _collect_names(arg.annotation, used)
    for default in [*args.defaults, *args.kw_defaults]:
        if default is not None:
            _collect_names(default, used, parse_strings=False)
    _collect_names(node.returns, used)


_STUB_DECORATORS = (
    "property",
    "staticmethod",
    "classmethod",
    "abstractmethod",
)


def _stub_docstring(doc: Optional[str]) -> Optional[str]:
    """First docstring sentence with Sphinx ``\\ `` escapes removed (a
    literal backslash would be an invalid escape in the stub source)."""
    sentence = _first_sentence(doc)
    return sentence.replace("\\ ", "") if sentence else None


def _stub_def(
    node: ast.FunctionDef,
    used: set[str],
    keep_docstring: bool = False,
    comment: str = "",
) -> list[str]:
    lines: list[str] = []
    for name in _decorator_names(node):
        if name == "cached_property":
            name = "property"
        if name in _STUB_DECORATORS or name.endswith(".setter"):
            lines.append(f"@{name}")
            if name == "abstractmethod":
                used.add(name)
    _collect_def_names(node, used)
    sig = f"def {node.name}({_fmt_args(node.args)})"
    if node.returns is not None:
        sig += f" -> {ast.unparse(node.returns)}"
    suffix = f"  # {comment}" if comment else ""
    sentence = (
        _stub_docstring(ast.get_docstring(node)) if keep_docstring else None
    )
    if sentence:
        lines += [f"{sig}:{suffix}", f'    """{sentence}"""']
    else:
        lines.append(f"{sig}: ...{suffix}")
    return lines


def _stub_class(
    cls: ast.ClassDef,
    used: set[str],
    extra: list[tuple[ast.FunctionDef, set[str], str]],
    defined: set[str],
) -> list[str]:
    lines: list[str] = []
    for deco in cls.decorator_list:
        target = deco.func if isinstance(deco, ast.Call) else deco
        if ast.unparse(target).split(".")[-1] == "dataclass":
            lines.append(f"@{ast.unparse(deco)}")
            _collect_names(deco, used, parse_strings=False)
    bases = []
    for base in cls.bases:
        text = ast.unparse(base)
        # Internal mixins are not rendered; their relevant public API is
        # appended via STUB_EXTRA_METHODS instead.
        if text.endswith("Mixin"):
            continue
        bases.append(text)
        _collect_names(base, used, parse_strings=False)
    header = f"class {cls.name}"
    if bases:
        header += f"({', '.join(bases)})"
    lines.append(f"{header}:")
    body: list[str] = []
    sentence = _stub_docstring(ast.get_docstring(cls))
    if sentence:
        body.append(f'"""{sentence}"""')
    is_enum = any(base in ("Enum", "IntEnum", "StrEnum") for base in bases)
    for node in cls.body:
        if isinstance(node, ast.AnnAssign) and isinstance(
            node.target, ast.Name
        ):
            name = node.target.id
            annotation = ast.unparse(node.annotation)
            if name.startswith("_") or annotation.startswith("ClassVar"):
                continue
            if (cls.name, name) in OMIT_MEMBERS:
                continue
            # Class constants (ADJ_CLOSE, COLUMNS, ...) may be referenced
            # by sibling class-attribute defaults in the same file.
            if name.isupper():
                defined.add(name)
            _collect_names(node.annotation, used)
            entry = f"{name}: {annotation}"
            default = _unwrap_field_default(node.value)
            if default is not None:
                _collect_names(node.value, used, parse_strings=False)
                entry += f" = {default}"
            body.append(entry)
        elif (
            is_enum
            and isinstance(node, ast.Assign)
            and len(node.targets) == 1
            and isinstance(node.targets[0], ast.Name)
            and not node.targets[0].id.startswith("_")
        ):
            body.append(ast.unparse(node))
    init = _find_init(cls)
    if cls.name in STUB_NO_INIT:
        body.append("# Constructed by the framework; not user-instantiable.")
    elif init is not None:
        body += _stub_def(init, used)
    attrs = _init_attrs(cls)
    if attrs:
        body.append("# Instance attributes assigned in __init__:")
        for name, annotation in attrs:
            _collect_names(annotation, used)
            body.append(f"{name}: {ast.unparse(annotation)}")
    for node in cls.body:
        if not _is_public_def(node) or node.name == "__init__":
            continue
        if (cls.name, node.name) in OMIT_MEMBERS:
            continue
        body += _stub_def(node, used)
    getattr_def = next(
        (
            node
            for node in cls.body
            if isinstance(node, ast.FunctionDef) and node.name == "__getattr__"
        ),
        None,
    )
    if getattr_def is not None:
        body += _stub_def(
            getattr_def, used, comment="registered custom columns"
        )
    for node, extra_used, extra_comment in extra:
        body += _stub_def(node, extra_used, comment=extra_comment)
    if not body:
        body = ["..."]
    lines += [f"    {line}" if line else "" for line in body]
    return lines


def _stub_member(tree: ast.Module, rel: str, name: str) -> ast.stmt:
    for node in tree.body:
        if (
            isinstance(node, (ast.ClassDef, ast.FunctionDef))
            and node.name == name
        ):
            return node
        if isinstance(node, ast.Assign) and any(
            isinstance(t, ast.Name) and t.id == name for t in node.targets
        ):
            return node
        if (
            isinstance(node, ast.AnnAssign)
            and isinstance(node.target, ast.Name)
            and node.target.id == name
        ):
            return node
    raise SystemExit(
        f"{rel}: no top-level definition named {name!r} "
        "(update STUBS in this script)"
    )


def _import_table(tree: ast.Module) -> dict[str, tuple[str, ...]]:
    """Maps names bound by non-pybroker imports anywhere in the module
    (including TYPE_CHECKING blocks) to import descriptors."""
    table: dict[str, tuple[str, ...]] = {}
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for alias in node.names:
                bound = alias.asname or alias.name.split(".")[0]
                table.setdefault(
                    bound, ("import", alias.name, alias.asname or "")
                )
        elif isinstance(node, ast.ImportFrom):
            if node.level or node.module is None:
                continue
            if node.module.split(".")[0] == "pybroker":
                continue
            for alias in node.names:
                bound = alias.asname or alias.name
                table.setdefault(
                    bound,
                    ("from", node.module, alias.name, alias.asname or ""),
                )
    return table


def _format_stub_imports(
    import_entries: set[tuple[str, ...]], siblings: dict[str, set[str]]
) -> list[str]:
    froms: dict[str, set[str]] = {}
    plains: set[str] = set()
    for entry in import_entries:
        if entry[0] == "import":
            _, module, asname = entry
            plains.add(
                f"import {module} as {asname}"
                if asname
                else f"import {module}"
            )
        else:
            _, module, name, asname = entry
            froms.setdefault(module, set()).add(
                f"{name} as {asname}" if asname else name
            )
    stdlib: list[str] = []
    third: list[str] = []
    for stmt in sorted(plains):
        module = stmt.split()[1]
        dest = (
            stdlib
            if module.split(".")[0] in sys.stdlib_module_names
            else third
        )
        dest.append(stmt)
    for module in sorted(froms):
        stmt = f"from {module} import {', '.join(sorted(froms[module]))}"
        dest = (
            stdlib
            if module.split(".")[0] in sys.stdlib_module_names
            else third
        )
        dest.append(stmt)
    stdlib.sort()
    third.sort()
    sibling_lines = [
        f"from {module} import {', '.join(sorted(names))}"
        for module, names in sorted(siblings.items())
    ]
    groups = [group for group in (stdlib, third, sibling_lines) if group]
    lines: list[str] = []
    for i, group in enumerate(groups):
        if i:
            lines.append("")
        lines += group
    return lines


def _resolve_stub_imports(
    fname: str,
    file_names: set[str],
    used: dict[Path, set[str]],
    trees: dict[Path, ast.Module],
    tables: dict[Path, dict[str, tuple[str, ...]]],
    name_to_stub: dict[str, str],
    repo: Path,
) -> tuple[list[str], list[str]]:
    """Returns (import lines, inline alias assignments) for a stub file,
    failing loudly on any name it cannot resolve."""
    defined = set(file_names)
    import_entries: set[tuple[str, ...]] = set()
    siblings: dict[str, set[str]] = {}
    inline: list[str] = []
    worklist: list[tuple[Path, str]] = []
    for path in sorted(used):
        worklist += [(path, name) for name in sorted(used[path])]
    queued = set(worklist)
    i = 0
    while i < len(worklist):
        path, name = worklist[i]
        i += 1
        if name in defined:
            continue
        if name in name_to_stub and name_to_stub[name] != fname:
            module = name_to_stub[name].removesuffix(".pyi")
            siblings.setdefault(module, set()).add(name)
            continue
        if name in STUB_OPAQUE:
            if fname != STUB_OPAQUE_HOME:
                module = STUB_OPAQUE_HOME.removesuffix(".pyi")
                siblings.setdefault(module, set()).add(name)
            continue
        if hasattr(builtins, name):
            continue
        table = tables[path]
        if name in table:
            import_entries.add(table[name])
            continue
        tree = trees[path]
        assign = next(
            (
                node
                for node in tree.body
                if (
                    isinstance(node, ast.Assign)
                    and any(
                        isinstance(t, ast.Name) and t.id == name
                        for t in node.targets
                    )
                )
                or (
                    isinstance(node, ast.AnnAssign)
                    and isinstance(node.target, ast.Name)
                    and node.target.id == name
                )
            ),
            None,
        )
        if assign is not None:
            inline.append(ast.unparse(assign))
            defined.add(name)
            new_names: set[str] = set()
            _collect_names(assign.value, new_names, parse_strings=False)
            for new_name in sorted(new_names):
                if (path, new_name) not in queued:
                    queued.add((path, new_name))
                    worklist.append((path, new_name))
            continue
        rel = path.relative_to(repo).as_posix()
        raise SystemExit(
            f"{fname}: cannot resolve name {name!r} (used via {rel}); "
            "add it to STUBS, STUB_OPAQUE, or the source imports"
        )
    return _format_stub_imports(import_entries, siblings), inline


def _render_stubs(repo: Path) -> dict[str, str]:
    paths = {repo / src for entries in STUBS.values() for src, _ in entries}
    for extras in STUB_EXTRA_METHODS.values():
        paths |= {repo / src for src, _, _ in extras}
    trees = {path: ast.parse(path.read_text()) for path in sorted(paths)}
    tables = {path: _import_table(tree) for path, tree in trees.items()}
    name_to_stub: dict[str, str] = {}
    for fname, entries in STUBS.items():
        for _, names in entries:
            for name in names:
                if name in name_to_stub:
                    raise SystemExit(f"duplicate name in STUBS: {name}")
                name_to_stub[name] = fname
    outputs: dict[str, str] = {}
    for fname, entries in STUBS.items():
        used: dict[Path, set[str]] = {}
        class_defined: set[str] = set()
        sections: list[str] = []
        for src, names in entries:
            path = repo / src
            module_used = used.setdefault(path, set())
            block = [f"# --- {src} ---"]
            for name in names:
                node = _stub_member(trees[path], src, name)
                if isinstance(node, ast.ClassDef):
                    extra = []
                    for esrc, ecls, emethods in STUB_EXTRA_METHODS.get(
                        name, []
                    ):
                        epath = repo / esrc
                        eused = used.setdefault(epath, set())
                        ecls_node = _stub_member(trees[epath], esrc, ecls)
                        assert isinstance(ecls_node, ast.ClassDef)
                        for method in emethods:
                            mnode = next(
                                n
                                for n in ecls_node.body
                                if isinstance(n, ast.FunctionDef)
                                and n.name == method
                            )
                            extra.append(
                                (mnode, eused, f"from {ecls} ({esrc})")
                            )
                    block += _stub_class(
                        node, module_used, extra, class_defined
                    )
                elif isinstance(node, ast.FunctionDef):
                    block += _stub_def(node, module_used, keep_docstring=True)
                else:
                    block.append(ast.unparse(node))
                    value = getattr(node, "value", None)
                    _collect_names(value, module_used)
                block.append("")
            sections.append("\n".join(block).rstrip())
        file_names = {
            name for _, names in entries for name in names
        } | class_defined
        if fname == STUB_OPAQUE_HOME:
            file_names |= STUB_OPAQUE
        import_lines, inline = _resolve_stub_imports(
            fname, file_names, used, trees, tables, name_to_stub, repo
        )
        parts = [STUB_HEADER, f'"""{STUB_TOPICS[fname]}"""', ""]
        parts += import_lines + [""]
        if inline:
            parts += inline + [""]
        if fname == STUB_OPAQUE_HOME:
            parts.append(
                "# Opaque internal types (referenced by signatures only)."
            )
            parts += [f"class {name}: ..." for name in sorted(STUB_OPAQUE)]
            parts.append("")
        parts += [f"{section}\n" for section in sections]
        content = "\n".join(parts).rstrip() + "\n"
        try:
            ast.parse(content)
        except SyntaxError as err:
            raise SystemExit(f"{fname}: generated stub does not parse: {err}")
        outputs[fname] = content
    return outputs


def _class_block(cls: ast.ClassDef, summarize: bool) -> list[str]:
    init = _find_init(cls)
    if init is not None:
        header = (
            f"### `class {cls.name}({_fmt_args(init.args, skip_self=True)})`"
        )
    else:
        header = f"### `class {cls.name}`"
    lines = [header, ""]
    sentence = _first_sentence(ast.get_docstring(cls))
    if sentence:
        lines += [sentence, ""]
    if summarize:
        return lines + [LOGGER_OMISSION_NOTE, ""]
    if _is_fieldlike_class(cls):
        bullets = _field_bullets(cls)
    else:
        bullets = [
            f"- `{name}: {ast.unparse(annotation)}`"
            for name, annotation in _init_attrs(cls)
        ]
    for node in cls.body:
        if not _is_public_def(node) or node.name == "__init__":
            continue
        if (cls.name, node.name) in OMIT_MEMBERS:
            continue
        decorators = _decorator_names(node)
        if "property" in decorators or "cached_property" in decorators:
            bullets.append(_property_bullets(node))
        elif any(name.endswith(".setter") for name in decorators):
            bullets.append(_property_bullets(node))
        elif "staticmethod" in decorators:
            bullets.append(_fn_bullet(node, skip_self=False))
        else:
            bullets.append(_fn_bullet(node, skip_self=True))
    if bullets:
        return lines + bullets + [""]
    return lines + [""]


def _render_api_module(
    repo: Path, module_path: Path, full_logger: bool
) -> list[str]:
    rel = module_path.relative_to(repo).as_posix()
    tree = ast.parse(module_path.read_text())
    lines = [f"## `{rel}`", ""]
    sentence = _first_sentence(ast.get_docstring(tree))
    if sentence:
        lines += [sentence, ""]
    fn_run: list[str] = []
    for node in tree.body:
        if isinstance(node, ast.ClassDef) and not node.name.startswith("_"):
            if fn_run:
                lines += fn_run + [""]
                fn_run = []
            summarize = (
                not full_logger
                and module_path.name == "log.py"
                and node.name == "Logger"
            )
            lines += _class_block(node, summarize)
        elif _is_public_def(node):
            fn_run.append(_fn_bullet(node, skip_self=False))
    if fn_run:
        lines += fn_run + [""]
    return lines


def _render_api(repo: Path, full_logger: bool) -> str:
    src = repo / "src" / "pybroker"
    modules = sorted(
        path for path in src.glob("*.py") if path.name != "__init__.py"
    )
    modules += sorted(
        path
        for path in (src / "ext").glob("*.py")
        if path.name != "__init__.py"
    )
    lines = API_HEADER.splitlines() + [""]
    for module_path in modules:
        lines += _render_api_module(repo, module_path, full_logger)
    while lines and not lines[-1]:
        lines.pop()
    return "\n".join(lines) + "\n"


def _build_outputs(
    repo: Path, only: str, full_logger: bool
) -> tuple[dict[Path, str], set[Path]]:
    """Returns generated {path: content} plus stale wiki paths to remove."""
    notebooks_dir = repo / "docs" / "source" / "notebooks"
    outputs: dict[Path, str] = {}
    stale: set[Path] = set()
    notebooks: list[tuple[Path, nbformat.NotebookNode]] = []
    if only in ("wiki", "index", "all"):
        notebooks = [
            (path, nbformat.read(path, as_version=4))
            for path in _notebook_paths(notebooks_dir)
        ]
    api_content = (
        _render_api(repo, full_logger) if only in ("api", "all") else None
    )
    stub_contents = _render_stubs(repo) if only in ("stubs", "all") else None
    for skill_name, cfg in SKILLS.items():
        references = repo / "skills" / skill_name / "references"
        if not references.is_dir():
            raise SystemExit(
                f"missing skill references dir: {references} "
                "(update SKILLS in this script)"
            )
        expected: set[Path] = set()
        entries: list[str] = []
        for nb_path, nb in notebooks:
            out_path = references / _wiki_filename(nb_path)
            if not cfg["all_wikis"] and not out_path.exists():
                continue
            expected.add(out_path)
            if only in ("wiki", "all"):
                outputs[out_path] = _render_wiki(nb_path, nb)
            entries.append(_index_entry(nb_path, nb))
        if cfg["index"] and only in ("index", "all"):
            index_path = references / "wiki-index.md"
            outputs[index_path] = _spliced_index(index_path, entries)
        if cfg["all_wikis"] and only in ("wiki", "all"):
            generated_pattern = re.compile(
                r"wiki-(\d{2}-[a-z0-9-]+|faqs)\.md$"
            )
            stale |= {
                path
                for path in references.glob("wiki-*.md")
                if generated_pattern.fullmatch(path.name)
                and path not in expected
            }
        if api_content is not None:
            api_path = references / "api-public-surface.md"
            if api_path.exists():
                outputs[api_path] = api_content
        if stub_contents is not None and cfg["stubs"]:
            for stub_name, content in stub_contents.items():
                outputs[references / stub_name] = content
            stale |= {
                path
                for path in references.glob("pybroker_*.pyi")
                if path.name not in stub_contents
            }
    return outputs, stale


def _check(outputs: dict[Path, str], stale: Iterable[Path]) -> int:
    drifted = []
    for path, content in sorted(outputs.items()):
        if not path.exists():
            drifted.append(f"missing: {path}")
        elif path.read_text() != content:
            drifted.append(f"differs: {path}")
    drifted.extend(f"stale: {path}" for path in sorted(stale))
    if drifted:
        print("\n".join(drifted))
        print(f"{len(drifted)} file(s) out of date; rerun without --check")
        return 1
    print(f"{len(outputs)} generated file(s) up to date")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--repo",
        type=Path,
        default=Path(__file__).resolve().parent.parent,
        help="pybroker repository root (default: this script's repo)",
    )
    parser.add_argument(
        "--only",
        choices=["wiki", "api", "index", "stubs", "all"],
        default="all",
        help="regenerate a subset of the reference files",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify generated files match disk; exit 1 on drift",
    )
    parser.add_argument(
        "--full-logger",
        action="store_true",
        help="emit every Logger method in api-public-surface.md",
    )
    args = parser.parse_args()
    outputs, stale = _build_outputs(args.repo, args.only, args.full_logger)
    if args.check:
        return _check(outputs, stale)
    for path, content in sorted(outputs.items()):
        changed = not path.exists() or path.read_text() != content
        path.write_text(content)
        print(f"{'wrote' if changed else 'unchanged'}: {path}")
    for path in sorted(stale):
        path.unlink()
        print(f"removed stale: {path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
